### PR TITLE
Homework28

### PR DESCRIPTION
**Pull request by pikadvert**
Homework28 by Karnazhevskyi Pavel

### CODE REVIEW

**Review by PonomaryovVladyslav — COMMENTED** [review]
__pycache__ cannot be in the git, should remove it

**Comment by pikadvert** [comment]
Pycache removed

**Comment by PonomaryovVladyslav** [comment]
Py cache cannot be in the git :)) check app folder

**Comment by pikadvert** [comment]
removed pycache from master branch

**Pull request merged**
